### ISSUE TITLE
the methods for sin/cos and Orthogonal are same with only different temperatures for q, k, v?

### ISSUE THREAD

**Issue by KK666-AI** [teddykoker/performer#1]
Dear author, thanks for the simple example for performer. It's really helpful.

the results of sin/cos and Orthogonal are generated via [the line](https://github.com/teddykoker/performer/blob/1c03bc26ccc481b945d6ffa256eb64933da0020e/performer.py#L123), and [the line](https://github.com/teddykoker/performer/blob/1c03bc26ccc481b945d6ffa256eb64933da0020e/performer.py#L171) respectively. It seems that the only difference for these two methods within the two experiments is the different temperature, the first is 1.5 and the second is 1.0. Is this correct? When I use temperature=1.5 for the second experiment, the performance of Orthogonal is much worse.

**Comment by teddykoker** [comment]
Sorry for the delay! Yes this is the correct; I was having trouble reproducing the results in the paper (as there is no mention of the temperature in the experiments), and one of the authors provided this detail. I presume orthogonal random features only benefits with a temperature  < 1, which is probably the case most of the time during training.
